### ISSUE TITLE
Address Information

### ISSUE THREAD

**Issue by jmitservices** [awsmug/alexa-sdk#1]
Hello,

Is it possible to use this code to request the address information?
[https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/device-address-api#testDeviceAddressAPI](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/device-address-api#testDeviceAddressAPI)

Thanks,
Jason

**Comment by mahype** [comment]
Hi Jason,

at the moment the API does not know permissions.

Greetings,

Sven
